### ISSUE TITLE
结果不对呀兄弟

### ISSUE THREAD

**Issue by hikari-He** [SteveRao/Compiling-Principle-Experiment#1]
结果不对呀兄弟，实验二语法分析里面，main函数后面最主要的那个while循环，flag直接被置1，然后就是analysis Failed!，另一方面那个Input.txt是不是也有问题呀，里面只有六个产生式，但是根据你发出来的运行结果图片，里面还用到了这六个之外的产生式。还有就是我愣是没找到你到底把 i+i*i 这个式子存在哪儿了。

**Comment by hikari-He** [comment]
你LL1.cpp和Input.txt的最后更新时间不一样，你是不是忘了更新Input.txt……

**Comment by steverao** [comment]
@WeiKaiTang 对，Input.txt中的数据与展示的是不一样的，另外，main函数中的flag没有直接被置1,一开始初始化是0,当两种情况发生时才置为1的。

**Comment by hikari-He** [comment]
嗯，我看到那两个if了，我的意思是它一开始就被触发了那两种情况中的一种，然后被置一了。

**Comment by steverao** [comment]
@WeiKaiTang 跑我的那个input里面的数据出错了吗？

**Comment by hikari-He** [comment]
我记得是的，而且这个程序好像从头到尾没输入i + i * i 这样的待分析语句，

**Comment by steverao** [comment]
你可以到教材中找一个相关的语法分析的例子，自己测试一下。我当时写的时候测试是没问题的，太久了一些东西都不记得了


在2019年06月15日 20:50，WeiKaiTang 写道：

我记得是的，而且这个程序好像从头到尾没输入i + i * i 这样的待分析语句，
